plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  Exclude:
    - 'vendor/**/*'

  TargetRubyVersion: 3.1

  NewCops: enable

Metrics:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Style/Documentation:
  Enabled: false
