name: build

on: [push, pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
        bundler-cache: true

    - name: Lint
      run: bundle exec rake rubocop

  test:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        ruby-version: ['3.1', '3.2', '3.3', '3.4', 'jruby']
        exclude:
          - os: windows-latest
            ruby-version: jruby

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Test
      run: bundle exec rake test

  test-vendor:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        ruby-version: ['3.1', '3.2', '3.3', '3.4', 'jruby']
        submodule:
          - vendor/github.com/rails/sprockets
          - vendor/github.com/sass/sassc-rails
          - vendor/github.com/twbs/bootstrap-rubygem
        exclude:
          - os: windows-latest
            ruby-version: jruby
          - os: windows-latest
            submodule: vendor/github.com/rails/sprockets
          - os: ubuntu-latest
            submodule: vendor/github.com/twbs/bootstrap-rubygem
          - os: windows-latest
            submodule: vendor/github.com/twbs/bootstrap-rubygem
          - ruby-version: jruby
            submodule: vendor/github.com/twbs/bootstrap-rubygem

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Test
      run: bundle exec rake git:submodule:test[${{matrix.submodule}}]

  release:

    if: github.event.repository.fork == false && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)

    needs: [lint, test, test-vendor]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
        ssh-key: ${{ secrets.DEPLOY_KEY }}

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby

    - name: Release
      run: |
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git config user.name github-actions[bot]
        rake -f -r bundler/gem_tasks release gem_push=no
